# Container image configuration
quarkus.container-image.build=true
quarkus.container-image.name=rimfrost-service-yrkanderoll
quarkus.container-image.tag=latest
quarkus.container-image.group=rimfrost
quarkus.container-image.push=false
# Choose registry (for pushing later)
# quarkus.container-image.registry=docker.io
